name: Unzip Files
on:
  push:
    paths:
      - '*.zip'
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unzip files
        run: |
          for zip in *.zip; do
            unzip -o "$zip" -d "${zip%.zip}"
            rm "$zip"
          done
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Unzip files" || echo "No changes to commit"
          git push
